# Generated by Django 5.2.4 on 2026-02-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='UserRegistration',
        ),
    ]
