# Generated by Django 5.2.4 on 2026-02-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0002_rename_registration_userregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Adventure', 'Adventure'), ('Honeymoon', 'Honeymoon'), ('Family', 'Family'), ('Spiritual', 'Spiritual')], max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='packages/')),
            ],
        ),
    ]
