# Generated by Django 5.2.11 on 2026-03-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0003_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('travel_date', models.CharField(max_length=100)),
                ('persons', models.IntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tours.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tours.userregistration')),
            ],
        ),
    ]
