# Generated by Django 5.2.11 on 2026-03-03 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_mode',
            field=models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight'), ('car', 'Car'), ('bike', 'Bike')], default='bus', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='available_seats',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='package',
            name='available_travel_modes',
            field=models.CharField(blank=True, help_text='Comma-separated travel modes', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='base_price',
            field=models.IntegerField(default=5000, help_text='Price per person'),
        ),
        migrations.AddField(
            model_name='package',
            name='max_persons',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='package',
            name='min_persons',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='persons',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
