# Generated by Django 5.2.11 on 2026-03-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0005_remove_package_price_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Honeymoon', 'Honeymoon'), ('Family', 'Family'), ('Spiritual', 'Spiritual'), ('SoloTrip', 'soloTrip')], max_length=100),
        ),
    ]
