# Generated by Django 5.2.11 on 2026-03-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0006_alter_package_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='available_travel_modes',
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Honeymoon', 'Honeymoon'), ('Family', 'Family'), ('Spiritual', 'Spiritual')], max_length=100),
        ),
    ]
