# Generated by Django 5.2.11 on 2026-03-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0007_remove_package_available_travel_modes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='package_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('vip', 'VIP')], default='standard', max_length=20),
        ),
    ]
