# Generated by Django 5.2.11 on 2026-03-03 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0008_booking_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='triptime',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 26, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
