# Generated by Django 5.2.11 on 2026-03-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0009_package_triptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Honeymoon', 'Honeymoon'), ('Family', 'Family'), ('Spiritual', 'Spiritual'), ('SoloTrip', 'SoloTrip')], max_length=100),
        ),
    ]
