# Generated by Django 5.2.11 on 2026-03-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0010_alter_package_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='source_city',
            field=models.CharField(blank=True, default='Ahmedabad', help_text='City where the tour starts', max_length=100),
        ),
    ]
