# Generated by Django 5.2.11 on 2026-03-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0011_package_source_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='source_city',
            field=models.CharField(default='Ahmedabad', help_text='City where the tour starts', max_length=100),
        ),
    ]
