# Generated by Django 5.2.11 on 2026-03-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0012_alter_package_source_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('hotel_name', models.CharField(blank=True, max_length=200)),
                ('breakfast', models.BooleanField(default=True)),
                ('lunch', models.BooleanField(default=True)),
                ('dinner', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_plans', to='Tours.package')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='DayPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='day_plans/gallery/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Tours.packagedayplan')),
            ],
        ),
    ]
