# Generated by Django 5.2.11 on 2026-03-04 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0013_packagedayplan_dayphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_type_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('package_type_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('refunded', 'Refunded')], default='paid', max_length=20)),
                ('payment_method', models.CharField(default='Online Payment', max_length=50)),
                ('invoice_items', models.JSONField(default=dict)),
                ('additional_charges', models.JSONField(blank=True, default=dict)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='Tours.booking')),
            ],
        ),
    ]
