# Generated by Django 5.2.11 on 2026-03-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0015_alter_invoice_base_amount_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='Tours_invoi_invoice_05bc63_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['booking'], name='Tours_invoi_booking_bf5668_idx'),
        ),
    ]
