# Generated by Django 5.2.11 on 2026-03-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0017_passengerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhar card number', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
