# Generated by Django 5.2.11 on 2026-03-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0018_userregistration_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_payment_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_code_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
