# Generated by Django 5.2.11 on 2026-03-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0019_booking_is_payment_complete_booking_payment_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_payment_complete',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_pin',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='qr_code_data',
        ),
    ]
