# Generated by Django 5.2.11 on 2026-03-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0020_remove_booking_is_payment_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
