# Generated by Django 5.2.11 on 2026-03-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0022_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('waiting', 'Waiting List')], default='confirmed', max_length=20),
        ),
    ]
