# Generated by Django 5.2.11 on 2026-03-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0023_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='promoted_from_waiting',
            field=models.BooleanField(default=False, help_text='Whether booking was promoted from waiting list'),
        ),
        migrations.AddField(
            model_name='booking',
            name='waiting_list_position',
            field=models.IntegerField(blank=True, help_text='Position in waiting list', null=True),
        ),
    ]
